const postsData = {
  posts: [
    {
      id: 10,
      title: "This is a test ",
      body: "Testing 123",
      created_at: "2022-01-07T08:13:30.100Z",
      updated_at: "2022-01-07T08:13:30.100Z",
      comment_count: 2,
      user: {
        id: 16,
        display_name: "rfox",
      },
    },
    {
      id: 13,
      title: "Yay!",
      body: "Testing is fun! 😀",
      created_at: "2022-01-07T08:20:19.344Z",
      updated_at: "2022-01-07T08:20:19.344Z",
      comment_count: 1,
      user: {
        id: 16,
        display_name: "rfox",
      },
    },
    {
      id: 7,
      title: "Clients are great!",
      body: "Try making it a bit less blah low resolution? It looks ok on my screen, or could you do an actual logo instead of a font i'll know it when i see it but make the font bigger and this turned out different that i decscribed but i love it, but can you invert all colors?.",
      created_at: "2021-12-29T07:55:57.618Z",
      updated_at: "2021-12-29T11:32:44.308Z",
      comment_count: 3,
      user: {
        id: 3,
        display_name: "Izzo",
      },
    },
    {
      id: 6,
      title: "The Anatomy of a Well-Engineered App",
      body: "Try making it a bit less blah low resolution? It looks ok on my screen, or could you do an actual logo instead of a font i'll know it when i see it but make the font bigger and this turned out different that i decscribed but i love it, but can you invert all colors?.",
      created_at: "2021-12-29T07:55:29.523Z",
      updated_at: "2021-12-29T11:33:07.033Z",
      comment_count: 3,
      user: {
        id: 3,
        display_name: "Izzo",
      },
    },
    {
      id: 5,
      title: "Last of the Mohicans",
      body: "Try making it a bit less blah low resolution? It looks ok on my screen, or could you do an actual logo instead of a font i'll know it when i see it but make the font bigger and this turned out different that i decscribed but i love it, but can you invert all colors?.",
      created_at: "2021-12-29T07:55:21.943Z",
      updated_at: "2021-12-29T11:33:18.135Z",
      comment_count: 1,
      user: {
        id: 3,
        display_name: "Izzo",
      },
    },
    {
      id: 4,
      title: "Extrapolation is the new Black",
      body: "Try making it a bit less blah low resolution? It looks ok on my screen, or could you do an actual logo instead of a font i'll know it when i see it but make the font bigger and this turned out different that i decscribed but i love it, but can you invert all colors?.",
      created_at: "2021-12-29T07:54:57.503Z",
      updated_at: "2021-12-29T11:33:33.265Z",
      comment_count: 0,
      user: {
        id: 3,
        display_name: "Izzo",
      },
    },
    {
      id: 2,
      title: "Return of the Suicide Squad",
      body: "Try making it a bit less blah low resolution? It looks ok on my screen, or could you do an actual logo instead of a font i'll know it when i see it but make the font bigger and this turned out different that i decscribed but i love it, but can you invert all colors?.",
      created_at: "2021-12-28T16:17:47.509Z",
      updated_at: "2021-12-29T11:33:56.109Z",
      comment_count: 8,
      user: {
        id: 3,
        display_name: "Izzo",
      },
    },
    {
      id: 1,
      title: "The Good, The Bad & The App",
      body: "Try making it a bit less blah low resolution? It looks ok on my screen, or could you do an actual logo instead of a font i'll know it when i see it but make the font bigger and this turned out different that i decscribed but i love it, but can you invert all colors?.",
      created_at: "2021-11-23T14:51:50.435Z",
      updated_at: "2021-12-29T11:34:20.657Z",
      comment_count: 2,
      user: {
        id: 1,
        display_name: "Rocky",
      },
    },
    {
      id: 15,
      title: "Single and Double Quotes in JavaScript Strings!",
      body: "Strings in JavaScript are contained within a pair of either single quotation marks '' or double quotation marks \"\". Both quotes represent Strings but be sure to choose one and STICK WITH IT. If you start with a single quote, you need to end with a single quote. There are pros and cons to using both IE single quotes tend to make it easier to write HTML within Javascript as you don’t have to escape the line with a double quote.\n",
      created_at: "2022-01-07T20:38:03.184Z",
      updated_at: "2022-01-07T20:40:33.245Z",
      comment_count: 1,
      user: {
        id: 16,
        display_name: "rfox",
      },
    },
    {
      id: 16,
      title: "One more test!",
      body: "This is just a test!",
      created_at: "2022-01-07T22:19:46.546Z",
      updated_at: "2022-01-07T22:19:58.091Z",
      comment_count: 2,
      user: {
        id: 16,
        display_name: "rfox",
      },
    },
    {
      id: 17,
      title: "new title",
      body: "new content",
      created_at: "2022-01-11T20:23:10.080Z",
      updated_at: "2022-01-11T20:23:10.080Z",
      comment_count: 2,
      user: {
        id: 27,
        display_name: "antmachine",
      },
    },
    {
      id: 9,
      title: "This is a Test",
      body: "Just some testing here...",
      created_at: "2022-01-07T07:34:49.094Z",
      updated_at: "2022-01-07T07:34:49.094Z",
      comment_count: 1,
      user: {
        id: 16,
        display_name: "rfox",
      },
    },
    {
      id: 18,
      title: "new 2",
      body: "content 2",
      created_at: "2022-01-11T20:23:58.576Z",
      updated_at: "2022-01-11T20:23:58.576Z",
      comment_count: 1,
      user: {
        id: 27,
        display_name: "antmachine",
      },
    },
    {
      id: 19,
      title: "My post from React",
      body: "Lorem ipsum...",
      created_at: "2022-01-12T20:12:58.263Z",
      updated_at: "2022-01-12T20:12:58.263Z",
      comment_count: 0,
      user: {
        id: 31,
        display_name: "abdul",
      },
    },
    {
      id: 20,
      title: "My post 1",
      body: "Lorem ipsum...",
      created_at: "2022-01-12T20:13:40.338Z",
      updated_at: "2022-01-12T20:13:40.338Z",
      comment_count: 0,
      user: {
        id: 31,
        display_name: "abdul",
      },
    },
    {
      id: 21,
      title: "My post 2",
      body: "Lorem ipsum...",
      created_at: "2022-01-12T20:13:45.902Z",
      updated_at: "2022-01-12T20:13:45.902Z",
      comment_count: 0,
      user: {
        id: 31,
        display_name: "abdul",
      },
    },
    {
      id: 8,
      title: "This is a post from React",
      body: "All software is built on a stack of technologies, and you need to understand enough of that stack to build your app. The reason why the React ecosystem of tooling seems overwhelming is because it’s always explained in the wrong order.",
      created_at: "2022-01-07T06:20:49.451Z",
      updated_at: "2022-01-07T07:55:19.817Z",
      comment_count: 7,
      user: {
        id: 16,
        display_name: "rfox",
      },
    },
    {
      id: 22,
      title: "My post 3",
      body: "Lorem ipsum...",
      created_at: "2022-01-12T20:13:51.811Z",
      updated_at: "2022-01-12T20:13:51.811Z",
      comment_count: 0,
      user: {
        id: 31,
        display_name: "abdul",
      },
    },
    {
      id: 23,
      title: "My post 4",
      body: "Lorem ipsum...",
      created_at: "2022-01-12T20:14:00.307Z",
      updated_at: "2022-01-12T20:14:00.307Z",
      comment_count: 0,
      user: {
        id: 31,
        display_name: "abdul",
      },
    },
  ],
  meta: {
    current_page: 1,
    per_page: 30,
    total_entries: 19,
  },
};
